// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    // { type: 'autogenerated', dirName: '.' },
    {
      type: 'doc',
      id: 'getting-started', // same as the file name (without .md)
      label: 'Getting Started',
    },
    // {
    //   type: 'doc',
    //   id: 'mugeshbabu',
    //   label: 'About',
    //   className: 'hidden',
    // },
    {
      type: 'category',
      label: 'Cable Service',
      items: ['cable/getting-started', 'cable/setup-box-guide', 'cable/recharge-guide', 'cable/troubleshooting', 'cable/faq'],
    },
    {
      type: 'category',
      label: 'Internet Service',
      items: ['internet/getting-started', 'internet/router-setup', 'internet/speed-issues', 'internet/faq'],
    },
    {
      type: 'category',
      label: 'Utility Payments',
      items: ['utility-payments/how-to-pay', 'utility-payments/refund-policy', 'utility-payments/faq'],
    },
    {
      type: 'category',
      label: 'Support & Policies',
      items: ['support/contact', 'support/privacy-policy', 'support/terms-of-service', 'support/cancellation-policy'],
    },
  ],
};

export default sidebars;
